services:
  - type: web
    name: unified-city-dashboard-api
    runtime: docker
    rootDir: backend
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: KAFKA_BOOTSTRAP_SERVERS
        sync: false
      - key: KAFKA_SECURITY_PROTOCOL
        value: SASL_SSL
      - key: KAFKA_SASL_MECHANISM
        value: PLAIN
      - key: KAFKA_USERNAME
        sync: false
      - key: KAFKA_PASSWORD
        sync: false
      - key: TOMTOM_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
